/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ioProject;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.FileReader;

public class App {

    public static void main(String[] args) {
        BufferedReader br = null;
        try {
            File file = new File("newFile.txt");
            
            if (!file.exists())
                file.createNewFile();
            
            PrintWriter pw = new PrintWriter(file);
            pw.println("The first file in java!");
            pw.println("Hello, teacher!");
            pw.println("!");
            pw.close();
            
            br = new BufferedReader(new FileReader("newFile.txt"));
            String line;
            
            while((line = br.readLine()) != null) {
                System.out.println(line);
            }
        } catch(IOException e) {
            System.out.print("Error: " + e);
        } finally {
            try {
                br.close();
            } catch (IOException e) {
                System.out.println("Error: " + e);
            }
        }
    }
}
